INSERT INTO candidates (name, experience, skills) VALUES
('Fredrick Wunsch', 7, '["Inventory Control","Lean Manufacturing","Environmental Regulations","Recycling Systems","Six Sigma","Logistics Coordination","OSHA Safety"]'),
('Tasha Jones', 5, '["Recycling Systems","Quality Assurance","Lean Manufacturing","Inventory Control","Six Sigma","ISO 14001"]'),
('Joy Strosin', 7, '["Process Optimization","Quality Assurance","Logistics Coordination","Inventory Control","ISO 14001"]'),
('Dr. Fernando Ernser', 2, '["Quality Assurance","Lean Manufacturing","Inventory Control","Supply Chain Pro"]'),
('Victor Conroy', 6, '["Logistics Coordination","Waste Management","Lean Manufacturing","Quality Assurance","Supply Chain Pro"]'),
('Sharon Friesen', 14, '["Team Leadership","Inventory Control","Environmental Regulations","Process Optimization","Logistics Coordination","Lean Expert"]'),
('Eloise Pagac', 10, '["Six Sigma","Team Leadership","Machine Operations","Recycling Systems","Lean Expert"]'),
('Adrienne Grady Sr.', 4, '["Process Optimization","Team Leadership","Six Sigma","Lean Manufacturing","ISO 14001"]'),
('Alexis Runolfsson', 11, '["Safety Compliance","Environmental Regulations","Lean Manufacturing","Six Sigma","Process Optimization","Recycling Systems","Supply Chain Pro"]'),
('Greg Toy DDS', 3, '["Logistics Coordination","Quality Assurance","Environmental Regulations","Machine Operations","Team Leadership","Inventory Control","Lean Expert"]'),
('Jared Dickinson', 3, '["Six Sigma","Inventory Control","Process Optimization","Safety Compliance","Environmental Regulations","Lean Expert"]'),
('Mr. Fredrick Littel', 14, '["Recycling Systems","Team Leadership","Safety Compliance","OSHA Safety"]'),
('Lila Farrell', 9, '["Logistics Coordination","Recycling Systems","Team Leadership","ISO 14001"]'),
('Leigh Beatty', 11, '["Quality Assurance","Logistics Coordination","Waste Management","Process Optimization","Supply Chain Pro"]'),
('Laurence Heaney', 2, '["Logistics Coordination","Team Leadership","Process Optimization","Six Sigma Green Belt"]'),
('Jamie Lehner', 14, '["Waste Management","Quality Assurance","Process Optimization","Six Sigma","Environmental Regulations","Team Leadership","Supply Chain Pro"]'),
('Emanuel Hills Jr.', 8, '["Quality Assurance","Team Leadership","Recycling Systems","Waste Management","Environmental Regulations","Supply Chain Pro"]'),
('Irene Hodkiewicz', 5, '["Waste Management","Recycling Systems","Safety Compliance","Environmental Regulations","Lean Expert"]'),
('Debbie Pfeffer', 10, '["Logistics Coordination","Quality Assurance","Lean Manufacturing","Recycling Systems","Environmental Regulations","Lean Expert"]'),
('Dr. Jimmie Price', 7, '["Quality Assurance","Logistics Coordination","Inventory Control","Environmental Regulations","Safety Compliance","Waste Management","OSHA Safety"]'),
('Julian DuBuque', 4, '["Waste Management","Safety Compliance","Inventory Control","Logistics Coordination","Machine Operations","Quality Assurance","OSHA Safety"]'),
('Dixie Klocko', 3, '["Logistics Coordination","Machine Operations","Lean Manufacturing","Quality Assurance","Process Optimization","Six Sigma Green Belt"]'),
('Emmett Mosciski', 5, '["Quality Assurance","Process Optimization","Waste Management","Safety Compliance","Lean Expert"]'),
('Gina Satterfield-Glover', 3, '["Environmental Regulations","Recycling Systems","Lean Manufacturing","Process Optimization","Lean Expert"]'),
('Ernesto Stark', 9, '["Logistics Coordination","Environmental Regulations","Lean Manufacturing","Six Sigma","Waste Management","ISO 14001"]'),
('Edward Schmeler', 9, '["Waste Management","Six Sigma","Inventory Control","Team Leadership","Machine Operations","OSHA Safety"]'),
('Dr. Willard Hansen', 13, '["Inventory Control","Machine Operations","Logistics Coordination","Environmental Regulations","Lean Manufacturing","Supply Chain Pro"]'),
('Verna Murphy', 10, '["Quality Assurance","Recycling Systems","Team Leadership","Supply Chain Pro"]'),
('Kristine Baumbach', 6, '["Team Leadership","Inventory Control","Process Optimization","Environmental Regulations","Supply Chain Pro"]'),
('Evelyn Jacobson', 15, '["Safety Compliance","Machine Operations","Waste Management","Inventory Control","Environmental Regulations","Team Leadership","Supply Chain Pro"]'),
('Rachael Jacobi', 8, '["Quality Assurance","Lean Manufacturing","Waste Management","Lean Expert"]'),
('Joe Murray', 10, '["Process Optimization","Machine Operations","Environmental Regulations","Supply Chain Pro"]'),
('Della Boehm', 13, '["Safety Compliance","Inventory Control","Logistics Coordination","Recycling Systems","Team Leadership","Quality Assurance","OSHA Safety"]'),
('Patti Ziemann-Dickinson', 6, '["Machine Operations","Process Optimization","Quality Assurance","Recycling Systems","Logistics Coordination","Safety Compliance","Six Sigma Green Belt"]'),
('Ms. Lynda Kub-Dickens', 15, '["Quality Assurance","Waste Management","Environmental Regulations","Lean Manufacturing","Inventory Control","Logistics Coordination","ISO 14001"]'),
('Shawna Padberg', 5, '["Quality Assurance","Recycling Systems","Lean Manufacturing","Team Leadership","Inventory Control","Machine Operations","OSHA Safety"]'),
('Al Huels III', 6, '["Lean Manufacturing","Six Sigma","Waste Management","Inventory Control","Lean Expert"]'),
('Rachel Lebsack', 15, '["Environmental Regulations","Lean Manufacturing","Process Optimization","Six Sigma","Quality Assurance","Recycling Systems","OSHA Safety"]'),
('Willie Beahan', 9, '["Safety Compliance","Lean Manufacturing","Team Leadership","Six Sigma Green Belt"]'),
('Dr. Dwight Bergnaum', 14, '["Lean Manufacturing","Safety Compliance","Waste Management","Supply Chain Pro"]');
